### ISSUE TITLE
Perform D8 gap analysis

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/views_data_export#1]
-Views is now in core
-Seralization is now in core

Identify gaps with Views to allow for a specific serialization format to be selected as a Views output

**Comment by jhedstrom** [comment]
This module (https://www.drupal.org/project/views_rest_feed) also by @grasmash appears to cover similar use-cases, but hasn't had a commit in about the same amount of time as this port. Any ideas where efforts should be focused?

**Comment by nerdstein** [comment]
@jhedstrom i think the modules are actually complementary. The latter, I believe, just adds some new serializations. @grasmash - any more clarity here?

**Comment by jhedstrom** [comment]
Ah, ok. I think I was thinking one would replace the other when I saw this one depends on REST as well.

**Comment by grasmash** [comment]
I also created the csv seriaization module to allow csv format for rest feeds. It works in combination with views rest feed.

**Comment by jhedstrom** [comment]
I've added a few issues that should at least get us to beta. Closing this out for now.
